// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example_sheet1.proto

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ExampleSheet1 struct {
	Id                   int32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Values               []int64               `protobuf:"varint,3,rep,packed,name=values,proto3" json:"values,omitempty"`
	Strings              []string              `protobuf:"bytes,4,rep,name=strings,proto3" json:"strings,omitempty"`
	Item                 *ExampleSheet1_Nested `protobuf:"bytes,5,opt,name=item,proto3" json:"item,omitempty"`
	Items                []*Item               `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ExampleSheet1) Reset()         { *m = ExampleSheet1{} }
func (m *ExampleSheet1) String() string { return proto.CompactTextString(m) }
func (*ExampleSheet1) ProtoMessage()    {}
func (*ExampleSheet1) Descriptor() ([]byte, []int) {
	return fileDescriptor_d145f073251048d8, []int{0}
}

func (m *ExampleSheet1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleSheet1.Unmarshal(m, b)
}
func (m *ExampleSheet1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleSheet1.Marshal(b, m, deterministic)
}
func (m *ExampleSheet1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleSheet1.Merge(m, src)
}
func (m *ExampleSheet1) XXX_Size() int {
	return xxx_messageInfo_ExampleSheet1.Size(m)
}
func (m *ExampleSheet1) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleSheet1.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleSheet1 proto.InternalMessageInfo

func (m *ExampleSheet1) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ExampleSheet1) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExampleSheet1) GetValues() []int64 {
	if m != nil {
		return m.Values
	}
	return nil
}

func (m *ExampleSheet1) GetStrings() []string {
	if m != nil {
		return m.Strings
	}
	return nil
}

func (m *ExampleSheet1) GetItem() *ExampleSheet1_Nested {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *ExampleSheet1) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type ExampleSheet1_Nested struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExampleSheet1_Nested) Reset()         { *m = ExampleSheet1_Nested{} }
func (m *ExampleSheet1_Nested) String() string { return proto.CompactTextString(m) }
func (*ExampleSheet1_Nested) ProtoMessage()    {}
func (*ExampleSheet1_Nested) Descriptor() ([]byte, []int) {
	return fileDescriptor_d145f073251048d8, []int{0, 0}
}

func (m *ExampleSheet1_Nested) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExampleSheet1_Nested.Unmarshal(m, b)
}
func (m *ExampleSheet1_Nested) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExampleSheet1_Nested.Marshal(b, m, deterministic)
}
func (m *ExampleSheet1_Nested) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExampleSheet1_Nested.Merge(m, src)
}
func (m *ExampleSheet1_Nested) XXX_Size() int {
	return xxx_messageInfo_ExampleSheet1_Nested.Size(m)
}
func (m *ExampleSheet1_Nested) XXX_DiscardUnknown() {
	xxx_messageInfo_ExampleSheet1_Nested.DiscardUnknown(m)
}

var xxx_messageInfo_ExampleSheet1_Nested proto.InternalMessageInfo

func (m *ExampleSheet1_Nested) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ExampleSheet1_Nested) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ExampleSheet1)(nil), "example.ExampleSheet1")
	proto.RegisterType((*ExampleSheet1_Nested)(nil), "example.ExampleSheet1.Nested")
}

func init() {
	proto.RegisterFile("example_sheet1.proto", fileDescriptor_d145f073251048d8)
}

var fileDescriptor_d145f073251048d8 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x4f, 0x4d, 0x4a, 0xc5, 0x30,
	0x10, 0x26, 0x4d, 0x9b, 0xc7, 0x9b, 0xe7, 0x73, 0x31, 0x88, 0x84, 0x82, 0x10, 0x74, 0x93, 0x85,
	0x04, 0x5a, 0xcf, 0xe0, 0xc2, 0x8d, 0x8b, 0x78, 0x00, 0xa9, 0x76, 0xd0, 0x40, 0xd3, 0x94, 0x26,
	0x8a, 0x77, 0xf6, 0x12, 0x62, 0x52, 0x05, 0x77, 0xae, 0x66, 0xbe, 0x3f, 0xe6, 0x1b, 0x38, 0xa3,
	0x8f, 0xc1, 0x2f, 0x13, 0x3d, 0xc6, 0x57, 0xa2, 0xd4, 0x99, 0x65, 0x0d, 0x29, 0xe0, 0x6e, 0x63,
	0xdb, 0x93, 0xe7, 0xe0, 0x7d, 0x98, 0x0b, 0x7d, 0xf9, 0xc9, 0xe0, 0x78, 0x5b, 0x94, 0x87, 0x6c,
	0xc7, 0x53, 0xa8, 0xdc, 0x28, 0x99, 0x62, 0xba, 0xb1, 0x95, 0x1b, 0x11, 0xa1, 0x9e, 0x07, 0x4f,
	0xb2, 0x52, 0x4c, 0xef, 0x6d, 0xde, 0xf1, 0x1c, 0xc4, 0xfb, 0x30, 0xbd, 0x51, 0x94, 0x5c, 0x71,
	0xcd, 0xed, 0x86, 0x50, 0xc2, 0x2e, 0xa6, 0xd5, 0xcd, 0x2f, 0x51, 0xd6, 0x8a, 0xeb, 0xbd, 0xfd,
	0x81, 0xd8, 0x41, 0xed, 0x12, 0x79, 0xd9, 0x28, 0xa6, 0x0f, 0xfd, 0x85, 0xd9, 0xda, 0x98, 0x3f,
	0xb7, 0xcd, 0x3d, 0xc5, 0x44, 0xa3, 0xcd, 0x56, 0xbc, 0x82, 0xe6, 0x7b, 0x46, 0x29, 0x14, 0xd7,
	0x87, 0xfe, 0xf8, 0x9b, 0xb9, 0x4b, 0xe4, 0x6d, 0xd1, 0xda, 0x6b, 0x10, 0x25, 0xf4, 0x9f, 0xde,
	0x4f, 0x22, 0x3f, 0x7d, 0xf3, 0x15, 0x00, 0x00, 0xff, 0xff, 0x74, 0x75, 0x16, 0xfd, 0x23, 0x01,
	0x00, 0x00,
}
